# Site settings
title: Austen Clark
email: Jesse@Clark.GURU
description: > # this means to ignore newlines until "baseurl:"
    Austen Site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://AustenClark.com" # the base hostname & protocol for your site
twitter_username: clarkguru
github_username:  clarkguru

# Build settings
markdown: kramdown
